import { useState } from 'react';
// import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
// import { Button } from '@/components/ui/button';
// import { Input } from '@/components/ui/input';
// import { Label } from '@/components/ui/label';
// import { Slider } from '@/components/ui/slider';
// import { Checkbox } from '@/components/ui/checkbox';
// import { Badge } from '@/components/ui/badge';
import { Moon, Clock, Star, Volume2 } from 'lucide-react';
// import { enhancedAPI } from '@/services/enhancedAPI';

interface SleepData {
  hours: number;
  quality: number;
  bedtime: string;
  issues: string[];
}

export function SleepAssessment() {
  const [sleepData, setSleepData] = useState<SleepData>({
    hours: 7,
    quality: 7,
    bedtime: '22:00',
    issues: []
  });
  
  const [results, setResults] = useState<any>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [audioUrl, setAudioUrl] = useState<string>('');

  const sleepIssues = [
    'Difficulty falling asleep',
    'Frequent wake-ups',
    'Early morning awakening',
    'Restless sleep',
    'Snoring',
    'Sleep apnea',
    'Nightmares',
    'Stress/anxiety',
    'Environmental noise',
    'Uncomfortable bed/pillow'
  ];

  const handleIssueChange = (issue: string, checked: boolean) => {
    setSleepData(prev => ({
      ...prev,
      issues: checked 
        ? [...prev.issues, issue]
        : prev.issues.filter(i => i !== issue)
    }));
  };

  const generateSleepAdvice = async () => {
    setIsLoading(true);
    // try {
    //   // Use enhanced Modal.com sleep analysis with $280 credits
    //   const advice = await enhancedAPI.getEnhancedSleepAdvice({
    //     ...sleepData,
    //     lifestyle_factors: ['regular_exercise'] // Add any lifestyle factors
    //   });
    //   setResults(advice);
      
    //   // Set meditation audio if generated by Modal.com
    //   if (advice.meditation_audio) {
    //     setAudioUrl(advice.meditation_audio);
    //   }
    // } catch (error) {
    //   console.error('Sleep assessment error:', error);
    // } finally {
    //   setIsLoading(false);
    // }
    // Mock functionality
    setResults({
      sleepScore: 75,
      analysis: "Mock analysis: Based on your input, your sleep is generally good, but could be improved by focusing on consistent bedtimes.",
      recommendations: ["Try to go to bed at the same time each night.", "Avoid caffeine in the evening."],
      modal_enhanced: false,
      circadian_insights: "Your bedtime is fairly consistent."
    });
    setIsLoading(false);
  };

  const getSleepScoreColor = (score: number) => {
    if (score >= 80) return 'text-green-600 bg-green-100';
    if (score >= 60) return 'text-yellow-600 bg-yellow-100';
    return 'text-red-600 bg-red-100';
  };

  const getSleepScoreDescription = (score: number) => {
    if (score >= 80) return 'Excellent Sleep';
    if (score >= 60) return 'Good Sleep';
    return 'Sleep Needs Improvement';
  };

  return (
    <div className="max-w-4xl mx-auto space-y-6">
      {/* <Card> */}
      <div className="border rounded-lg p-4">
        {/* <CardHeader> */}
        <div>
          {/* <CardTitle className="flex items-center gap-2"> */}
          <h2 className="text-xl font-semibold flex items-center gap-2">
            <Moon className="w-6 h-6 text-purple-600" />
            Sleep Quality Assessment (UI Elements Commented)
          </h2>
          {/* </CardTitle> */}
          <p className="text-gray-600">
            Get personalized sleep coaching and optimization recommendations
          </p>
        </div>
        {/* </CardHeader> */}
        {/* <CardContent className="space-y-6"> */}
        <div className="space-y-6 mt-4">
          {/* Sleep Hours */}
          <div className="space-y-2">
            {/* <Label>How many hours did you sleep last night?</Label> */}
            <div>How many hours did you sleep last night?</div>
            <div className="flex items-center space-x-4">
              {/* <Slider
                value={[sleepData.hours]}
                onValueChange={(value: number[]) => setSleepData(prev => ({ ...prev, hours: value[0] }))}
                max={12}
                min={1}
                step={0.5}
                className="flex-1"
              /> */}
              <input type="range" min="1" max="12" step="0.5" value={sleepData.hours} onChange={(e) => setSleepData(prev => ({ ...prev, hours: +e.target.value }))} />
              {/* <Badge variant="outline" className="min-w-[60px]"> */}
              <span className="border px-2 py-1 rounded min-w-[60px]">
                {sleepData.hours} hrs
              </span>
              {/* </Badge> */}
            </div>
          </div>

          {/* Sleep Quality */}
          <div className="space-y-2">
            {/* <Label>How would you rate your sleep quality? (1-10)</Label> */}
            <div>How would you rate your sleep quality? (1-10)</div>
            <div className="flex items-center space-x-4">
              {/* <Slider
                value={[sleepData.quality]}
                onValueChange={(value: number[]) => setSleepData(prev => ({ ...prev, quality: value[0] }))}
                max={10}
                min={1}
                step={1}
                className="flex-1"
              /> */}
              <input type="range" min="1" max="10" step="1" value={sleepData.quality} onChange={(e) => setSleepData(prev => ({ ...prev, quality: +e.target.value }))} />
              {/* <Badge variant="outline" className="min-w-[60px]"> */}
              <span className="border px-2 py-1 rounded min-w-[60px]">
                {sleepData.quality}/10
              </span>
              {/* </Badge> */}
            </div>
          </div>

          {/* Bedtime */}
          <div className="space-y-2">
            {/* <Label htmlFor="bedtime">What time did you go to bed?</Label> */}
            <label htmlFor="bedtime">What time did you go to bed?</label>
            <div className="flex items-center space-x-2">
              <Clock className="w-4 h-4 text-gray-400" />
              {/* <Input
                id="bedtime"
                type="time"
                value={sleepData.bedtime}
                onChange={(e: React.ChangeEvent<HTMLInputElement>) => setSleepData(prev => ({ ...prev, bedtime: e.target.value }))}
                className="w-32"
              /> */}
              <input id="bedtime" type="time" value={sleepData.bedtime} onChange={(e: React.ChangeEvent<HTMLInputElement>) => setSleepData(prev => ({ ...prev, bedtime: e.target.value }))} className="w-32 border p-1" />
            </div>
          </div>

          {/* Sleep Issues */}
          <div className="space-y-3">
            {/* <Label>What sleep issues did you experience? (Select all that apply)</Label> */}
            <div>What sleep issues did you experience? (Select all that apply)</div>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
              {sleepIssues.map((issue) => (
                <div key={issue} className="flex items-center space-x-2">
                  {/* <Checkbox
                    id={issue}
                    checked={sleepData.issues.includes(issue)}
                    onCheckedChange={(checked: boolean | 'indeterminate') =>
                      handleIssueChange(issue, checked as boolean)
                    }
                  /> */}
                  <input type="checkbox" id={issue} checked={sleepData.issues.includes(issue)} onChange={(e) => handleIssueChange(issue, e.target.checked)} />
                  {/* <Label htmlFor={issue} className="text-sm font-normal cursor-pointer"> */}
                  <label htmlFor={issue} className="text-sm font-normal cursor-pointer">
                    {issue}
                  </label>
                  {/* </Label> */}
                </div>
              ))}
            </div>
          </div>

          {/* <Button
            onClick={generateSleepAdvice} 
            disabled={isLoading}
            className="w-full"
          > */}
          <button onClick={generateSleepAdvice} disabled={isLoading} className="w-full p-2 bg-blue-500 text-white rounded disabled:bg-gray-300">
            {isLoading ? 'Analyzing your sleep...' : 'Get Sleep Coaching'}
          </button>
          {/* </Button> */}
        </div>
        {/* </CardContent> */}
      </div>
      {/* </Card> */}

      {/* Results */}
      {results && (
        // <Card>
        <div className="border rounded-lg p-4 mt-6">
          {/* <CardHeader> */}
          <div>
            {/* <CardTitle className="flex items-center gap-2"> */}
            <h3 className="text-lg font-semibold flex items-center gap-2">
              <Star className="w-6 h-6 text-yellow-500" />
              Your Sleep Analysis
            </h3>
            {/* </CardTitle> */}
          </div>
          {/* </CardHeader> */}
          {/* <CardContent className="space-y-6"> */}
          <div className="space-y-6 mt-4">
            {/* Sleep Score */}
            <div className="text-center">
              {/* <div className={`inline-flex items-center px-4 py-2 rounded-full text-2xl font-bold ${getSleepScoreColor(results.sleepScore)}`}> */}
              <div className={`inline-flex items-center px-4 py-2 rounded-full text-2xl font-bold ${getSleepScoreColor(results.sleepScore)}`}>
                {results.sleepScore}/100
              </div>
              <p className="text-lg font-medium mt-2">
                {getSleepScoreDescription(results.sleepScore)}
              </p>
            </div>

            {/* Analysis */}
            <div className="bg-blue-50 p-4 rounded-lg">
              <div className="flex items-center justify-between mb-2">
                <h3 className="font-semibold text-blue-900">Sleep Analysis</h3>
                {results.modal_enhanced && (
                  // <Badge className="bg-purple-100 text-purple-800">
                  <span className="px-2 py-1 text-xs bg-purple-100 text-purple-800 rounded">
                    ✨ Modal.com Enhanced
                  </span>
                  // </Badge>
                )}
              </div>
              <p className="text-blue-800 whitespace-pre-wrap">{results.analysis}</p>
              {results.circadian_insights && (
                <div className="mt-3 p-3 bg-blue-100 rounded">
                  <h4 className="font-medium text-blue-900 mb-1">Circadian Insights</h4>
                  <p className="text-blue-800 text-sm">{results.circadian_insights}</p>
                </div>
              )}
            </div>

            {/* Recommendations */}
            {results.recommendations.length > 0 && (
              <div>
                <h3 className="font-semibold mb-3">Personalized Recommendations</h3>
                <div className="space-y-2">
                  {results.recommendations.map((rec: string, index: number) => (
                    <div key={index} className="flex items-start gap-2 p-3 bg-gray-50 rounded-lg">
                      <div className="w-2 h-2 bg-purple-500 rounded-full mt-2 flex-shrink-0" />
                      <p className="text-sm">{rec}</p>
                    </div>
                  ))}
                </div>
              </div>
            )}

            {/* Meditation Audio */}
            {audioUrl && (
              <div className="bg-purple-50 p-4 rounded-lg">
                <h3 className="font-semibold text-purple-900 mb-2 flex items-center gap-2">
                  <Volume2 className="w-4 h-4" />
                  Personalized Sleep Meditation
                </h3>
                <p className="text-purple-800 text-sm mb-3">
                  Since your sleep quality could be improved, I've generated a personalized meditation to help you relax.
                </p>
                <audio controls className="w-full">
                  <source src={audioUrl} type="audio/mpeg" />
                  Your browser does not support the audio element.
                </audio>
              </div>
            )}
          </div>
          {/* </CardContent> */}
        </div>
        // </Card>
      )}

      {/* Tips Card */}
      {/* <Card> */}
      <div className="border rounded-lg p-4 mt-6">
        {/* <CardContent className="p-4"> */}
        <div className="p-4">
          <div className="flex items-start gap-3">
            <Moon className="w-5 h-5 text-purple-500 mt-0.5" />
            <div>
              <h3 className="font-medium text-gray-900">Sleep Hygiene Tips</h3>
              <ul className="text-sm text-gray-600 mt-1 space-y-1">
                <li>• Maintain a consistent sleep schedule</li>
                <li>• Create a cool, dark, and quiet sleeping environment</li>
                <li>• Avoid screens 1 hour before bedtime</li>
                <li>• Limit caffeine intake after 2 PM</li>
                <li>• Practice relaxation techniques before bed</li>
              </ul>
            </div>
          </div>
        </div>
        {/* </CardContent> */}
      </div>
      {/* </Card> */}
    </div>
  );
}